# Generated by Django 3.0.8 on 2020-07-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessRescord',
            new_name='AccessRecord',
        ),
    ]
